RepairShop/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RepairShop.Models
{
    public class User
    {
		public User()
		{
			Devices = new HashSet<Device>();
		}
        #region Properties

        [Required]
        public long Id { get; set; }

		[Required]
		[StringLength(30)]
		public string UserName { get; set; }

        [Required]
        public string Name { get; set; }

		[Required]
		public string Password { get; set; }

        public string Address { get; set; }

        [Phone(ErrorMessage = "Invalid phone number.")]
        public string Phone { get; set; }

        [EmailAddress(ErrorMessage = "Invalid email address")]
		[Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

		public string UserType { get; set; }
		#endregion

		#region Children
		public ICollection<Device> Devices { get; set; }
		#endregion
	}
}

RepairShop/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RepairShop.Data;
using RepairShop.Models;
using RepairShop.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace RepairShop.Controllers
{
    public class DevicesController : BaseController
    {
        private readonly RepairShopContext _context;

        public DevicesController(RepairShopContext context)
        {
            _context = context;    
        }

        // GET: Devices
        public async Task<IActionResult> Index()
        {
            var repairShopContext = _context.Devices.Include(d => d.User);
            return View(await repairShopContext.ToListAsync());
        }

        // GET: Devices/Details/5
        public async Task<IActionResult> Details(long? id, string sortOrder, int? page = 1)
        {
            if (id == null)
            {
                return NotFound();
            }

			if (String.IsNullOrWhiteSpace(sortOrder))
			{
				sortOrder = "endDate";
			}

			ViewData["CurrentSort"] = sortOrder;
			ViewData["ServiceTitleSortParm"] = sortOrder == "serviceTitle" ? "serviceTitle_Desc" : "serviceTitle";
			ViewData["StartDateSortParm"] = sortOrder == "startDate" ? "startDate_desc" : "startDate";
			ViewData["EndDateSortParm"] = sortOrder == "endDate" ? "endDate_desc" : "endDate";
			ViewData["CostSortParm"] = sortOrder == "cost" ? "cost_desc" : "cost";


			var device = await _context.Devices
                .Include(d => d.User)
                .SingleOrDefaultAsync(m => m.Id == id);

			if(device == null)
			{
				return NotFound();
			}

			var deviceServices = _context.DeviceServices
				.Include(d => d.Service)
				.Where(ds => ds.DeviceId == device.Id);

			switch (sortOrder)
			{
				case "serviceTitle":
					deviceServices = deviceServices.OrderBy(ds => ds.Service.Title);
					break;
				case "serviceTitle_Desc":
					deviceServices = deviceServices.OrderByDescending(ds => ds.Service.Title);
					break;
				case nameof(DeviceService.DateOrdered):
					deviceServices = deviceServices.OrderBy(ds => ds.DateOrdered);
					break;
				case nameof(DeviceService.DateOrdered) + "_desc":
					deviceServices = deviceServices.OrderByDescending(ds => ds.DateOrdered);
					break;
				case "cost":
					deviceServices = deviceServices.OrderBy(ds => ds.Service.Price);
					break;
				case "cost_desc":
					deviceServices = deviceServices.OrderByDescending(ds => ds.Service.Price);
					break;
				default:
					deviceServices = deviceServices.OrderByDescending(ds => ds.DateOrdered);
					break;
			}
			int pageSize = 4;

			var deviceDetails = new DeviceDetailViewModel();
			deviceDetails.Device = device;
			deviceDetails.DeviceServices = await PaginatedList<DeviceService>.CreateAsync(deviceServices.AsNoTracking(), page ?? 1, pageSize);
			return View(deviceDetails);
		}

		

		// GET: Devices/Create
		public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name");
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,SerialNbr,Type,Make,Model")] Device device)
        {
            if (ModelState.IsValid)
            {
                _context.Add(device);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name", device.UserId);
            return View(device);
        }

        // GET: Devices/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var device = await _context.Devices.SingleOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name", device.UserId);
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,UserId,SerialNbr,Type,Make,Model")] Device device)
        {
            if (id != device.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(device);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceExists(device.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name", device.UserId);
            return View(device);
        }

        // GET: Devices/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var device = await _context.Devices
                .Include(d => d.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var device = await _context.Devices.SingleOrDefaultAsync(m => m.Id == id);
            _context.Devices.Remove(device);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool DeviceExists(long id)
        {
            return _context.Devices.Any(e => e.Id == id);
        }
    }
}

RepairShop/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RepairShop.Data;
using RepairShop.Models;
using RepairShop.Models.ViewModels;
using Microsoft.AspNetCore.Http;

namespace RepairShop.Controllers
{
    public class UsersController : BaseController
    {
        private readonly RepairShopContext _context;

        public UsersController(RepairShopContext context)
        {
            _context = context;    
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

			var userDetail = new UserDetailViewModel();

            var user = await _context.Users
				.AsNoTracking()
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
			userDetail.User = user;
			userDetail.Devices = _context.Devices
				.AsNoTracking()
				.Where(d => d.UserId == user.Id).ToList();
			userDetail.TotalEarned = _context.DeviceServices
				.AsNoTracking()
				.Where(ds => ds.Device.UserId == user.Id)
				.Sum(ds => ds.Service.Price);

            return View(userDetail);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Phone,EmailAddress")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Address,Phone,EmailAddress")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

		public IActionResult Login(string controller = "Home", string action = "Index")
		{
			return View(new User());
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Login([Bind("UserName,Password")] User user)
		{
			try
			{
				if (!String.IsNullOrWhiteSpace(user.UserName) && !String.IsNullOrWhiteSpace(user.Password))
				{
					var foundUser = await _context.Users.SingleOrDefaultAsync(u => u.UserName.ToLower() == user.UserName.ToLower());
					if (foundUser != null)
					{
						if (foundUser.Password == user.Password)
						{
							HttpContext.Session.SetString(SessionKeyUserName, foundUser.UserName);
							HttpContext.Session.SetString(SessionKeyUserId, foundUser.Id.ToString());
						}
						else
						{
							throw new UnauthorizedAccessException();
						}
					}
					else
					{
						throw new UnauthorizedAccessException();
					}
				}
				else
				{
					throw new UnauthorizedAccessException();
				}
			}
			catch (UnauthorizedAccessException)
			{
				return RedirectToAction("Login");
			}
			return RedirectToAction("Index", "Home", new { area = "" });

		}

		public IActionResult Logout([Bind("UserName,Password")] User user)
		{
			HttpContext.Session.Clear();
			return RedirectToAction("Index", "Home", new { area = "" });
		}

		private bool UserExists(long id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

RepairShop/Views/Users/Create.cshtml
@model RepairShop.Models.User

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairShop/Views/Users/Delete.cshtml
@model RepairShop.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

RepairShop/Views/Users/Details.cshtml
@model RepairShop.Models.ViewModels.UserDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
	<div class="row">
		<div class="col-md-6">
			<dl class="dl-horizontal">
				<dt>
					@Html.DisplayNameFor(model => model.User.Name)
				</dt>
				<dd>
					@Html.DisplayFor(model => model.User.Name)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.User.Address)
				</dt>
				<dd>
					@Html.DisplayFor(model => model.User.Address)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.User.Phone)
				</dt>
				<dd>
					@Html.DisplayFor(model => model.User.Phone)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.User.EmailAddress)
				</dt>
				<dd>
					@Html.DisplayFor(model => model.User.EmailAddress)
				</dd>
			</dl>
		</div>
		<div class="col-md-6">
			<dl class="dl-horizontal">
				<dt>
					@Html.DisplayNameFor(model => model.TotalEarned)
				</dt>
				<dd>
					@Html.DisplayFor(model => model.TotalEarned)
				</dd>
			</dl>
		</div>
	</div>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.User.Id">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>
<hr/>
<h4>Devices</h4>
<div>
	<table class="table">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Devices.First().Make)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Devices.First().Model)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Devices.First().Type)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Devices.First().SerialNbr)
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Devices)
			{
				<tr>
					
					<td>
						@Html.DisplayFor(modelItem => item.Make)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Model)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Type)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.SerialNbr)
					</td>
					<td>
						<a asp-controller="Devices" asp-action="Details" asp-route-id="@item.Id">Details</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

RepairShop/Views/Users/Edit.cshtml
@model RepairShop.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepairShop/Views/Users/Index.cshtml
@model IEnumerable<RepairShop.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EmailAddress)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RepairShop/Views/Users/Login.cshtml
@model RepairShop.Models.User
<h2>Login</h2>

<form asp-action="Login">
	<div class="form-group">
		<label asp-for="UserName"></label><br/>
		<input asp-for="UserName" class="form-control"/><br /><br />
		<label asp-for="Password">Password</label><br />
		<input asp-for="Password" type="password" class="form-control"/><br /><br />
		<input class="btn btn-primary" type="submit" value="Submit"/>
	</div>

</form>